version: 2
services:
  - type: web
    name: trackzen-api
    runtime: node
    plan: starter
    buildCommand: npm run build:server
    startCommand: npm start
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: "18"
    # Add your environment variables here
    # Example:
    # - key: MONGODB_URI
    #   value: your_mongodb_connection_string
    # - key: JWT_SECRET
    #   value: your_jwt_secret
    # - key: DATABASE_URL
    #   value: your_database_url
