name: Deploy TrackZen to Netlify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run typecheck
      continue-on-error: true # Don't fail deployment on type errors

    - name: Build project
      run: npm run build:netlify
      env:
        NODE_ENV: production

    - name: Deploy to Netlify (Preview)
      if: github.event_name == 'pull_request'
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist/spa --alias=preview-${{ github.event.number }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: d3da4e1f-f57b-46c4-aec0-232a99d5cd4f

    - name: Deploy to Netlify (Production)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist/spa --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: d3da4e1f-f57b-46c4-aec0-232a99d5cd4f

    - name: Comment PR with preview link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 **TrackZen Preview Deployment Ready!**\n\n📱 Preview URL: https://preview-${{ github.event.number }}--trackzen-pms-dashboard.netlify.app\n\n✅ Changes from this PR are live and ready for testing!'
          })

    - name: Update deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful!"
          echo "🌐 Production URL: https://trackzen-pms-dashboard.netlify.app"
        else
          echo "❌ Deployment failed!"
        fi
